swiftmailer:
    #url: '%env(MAILER_URL)%'
    spool: { type: 'memory' }
    transport:        smtp
    username:         "angelesmu1992@gmail.com"
    password:         "Kevinjaen1"
    host:            "smtp.gmail.com"
    port:             587
    encryption:       tls
    auth-mode:        login
    stream_options:
        ssl:
            allow_self_signed: true
            verify_peer: false
            verify_peer_name: false